#!/usr/bin/env bash
# ============================================================
# precompact_save_state.sh — コンパクション前の作業状態保全
# ============================================================
# PreCompact hookから呼ばれ、エージェントの現在状態をYAMLに保存する。
# コンパクション復帰時にこのファイルを読めば、正データ確認の補助になる。
#
# 保存先: /tmp/shogun_precompact_{agent_id}.yaml
# stdin: { "session_id": "...", "trigger": "manual|auto" }

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"

# エージェント情報取得
AGENT_ID=$(tmux display-message -t "$TMUX_PANE" -p '#{@agent_id}' 2>/dev/null || echo "unknown")
ARMY_ID=$(tmux display-message -t "$TMUX_PANE" -p '#{@army_id}' 2>/dev/null || echo "")
TIMESTAMP=$(date "+%Y-%m-%dT%H:%M:%S")

# stdin読み取り
INPUT=$(cat)
TRIGGER=$(python3 -c "
import json, sys
try:
    data = json.loads(sys.argv[1])
    print(data.get('trigger', 'unknown'))
except:
    print('unknown')
" "$INPUT" 2>/dev/null || echo "unknown")

OUT="/tmp/shogun_precompact_${AGENT_ID}.yaml"

# タスクYAMLパスとstatusを特定
TASK_FILE=""
TASK_STATUS=""
TASK_ID=""

case "$AGENT_ID" in
  ashigaru*)
    NUM=$(echo "$AGENT_ID" | grep -oP '\d+$')
    if [ -n "$ARMY_ID" ]; then
      SUFFIX="${ARMY_ID: -1}"
      # armyA: ashigaru{N}.yaml / armyB: ashigaruB{N}.yaml / armyC: ashigaruC{N}.yaml
      if [ "$SUFFIX" = "A" ]; then
        TASK_FILE="$BASE_DIR/queue/${ARMY_ID}/tasks/ashigaru${NUM}.yaml"
      else
        TASK_FILE="$BASE_DIR/queue/${ARMY_ID}/tasks/ashigaru${SUFFIX}${NUM}.yaml"
      fi
    fi
    ;;
  karo*)
    if [ -n "$ARMY_ID" ]; then
      TASK_FILE="$BASE_DIR/queue/${ARMY_ID}/shogun_to_karo.yaml"
    fi
    ;;
  shogun*)
    TASK_FILE="$BASE_DIR/queue/taishogun_to_shogun.yaml"
    ;;
  taishogun)
    TASK_FILE="$BASE_DIR/queue/taishogun_to_shogun.yaml"
    ;;
esac

if [ -n "$TASK_FILE" ] && [ -f "$TASK_FILE" ]; then
  # YAML value extraction: supports various indent levels, quoted/unquoted values
  # Pattern: optional whitespace + key: + optional whitespace + value (strip quotes)
  extract_yaml_value() {
    local file="$1" key="$2"
    grep -m1 "^[[:space:]]*${key}:" "$file" 2>/dev/null \
      | sed "s/^[[:space:]]*${key}:[[:space:]]*//" \
      | sed "s/^['\"]//; s/['\"]$//" \
      | sed 's/[[:space:]]*$//' \
      || echo ""
  }

  TASK_STATUS=$(extract_yaml_value "$TASK_FILE" "status")
  [ -z "$TASK_STATUS" ] && TASK_STATUS="unknown"

  TASK_ID=$(extract_yaml_value "$TASK_FILE" "task_id")
  if [ -z "$TASK_ID" ]; then
    # fallback: try "- id:" list format
    TASK_ID=$(grep -m1 '^\s*-\s*id:' "$TASK_FILE" 2>/dev/null \
      | sed 's/^[[:space:]]*-[[:space:]]*id:[[:space:]]*//' \
      | sed "s/^['\"]//; s/['\"]$//" \
      | sed 's/[[:space:]]*$//' \
      || echo "unknown")
  fi
fi

# git diff で変更中ファイルを取得
CHANGED_FILES=$(cd "$BASE_DIR" && git diff --name-only 2>/dev/null | head -20 || echo "")
STAGED_FILES=$(cd "$BASE_DIR" && git diff --cached --name-only 2>/dev/null | head -20 || echo "")

# YAML出力
cat > "$OUT" << YAML
# PreCompact State Snapshot
# Auto-generated by precompact_save_state.sh
agent_id: "${AGENT_ID}"
army_id: "${ARMY_ID}"
timestamp: "${TIMESTAMP}"
trigger: "${TRIGGER}"
task:
  file: "${TASK_FILE}"
  task_id: "${TASK_ID}"
  status: "${TASK_STATUS}"
git_changes:
  modified:
YAML

if [ -n "$CHANGED_FILES" ]; then
  echo "$CHANGED_FILES" | while IFS= read -r f; do
    echo "    - \"$f\"" >> "$OUT"
  done
else
  echo "    []" >> "$OUT"
fi

cat >> "$OUT" << YAML
  staged:
YAML

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | while IFS= read -r f; do
    echo "    - \"$f\"" >> "$OUT"
  done
else
  echo "    []" >> "$OUT"
fi

exit 0
